# Official documentation at http://goreleaser.com
project_name: rtask
builds:
  - env:
      - CGO_ENABLED=0
    binary: rtask
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    ignore:
      - goarch: arm
      - goarch: arm64
      - goarch: 386
    ldflags:
      - -w
      - -s
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"